---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: roboshop
  labels:
    app: web
    project: roboshop
    tier: web  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      project: roboshop
      tier: web
  template:
    metadata:
      labels:
        app: catalogue
        project: roboshop
        tier: web  
    spec:
      containers:
      - name: web
        image: rajeshkalavapalli/web:v1
        imagePullPolicy: Always
        # envFrom:
        # - configMapRef:
        #     name: web
---
apiVersion: v1
kind: Service
metadata:  
  name: web
  namespace: roboshop
spec:
  type: LoadBalancer
  selector:
    app: web
    project: roboshop
    tier: web 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      